// q_sys_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module q_sys_mm_interconnect_0 (
		input  wire        sys_clk_clk_clk,                                        //                                sys_clk_clk.clk
		input  wire        sensor_interface_rst_reset_bridge_in_reset_reset,       // sensor_interface_rst_reset_bridge_in_reset.reset
		input  wire [8:0]  sensor_interface_calibration_ram_interface_address,     // sensor_interface_calibration_ram_interface.address
		output wire        sensor_interface_calibration_ram_interface_waitrequest, //                                           .waitrequest
		input  wire        sensor_interface_calibration_ram_interface_read,        //                                           .read
		output wire [15:0] sensor_interface_calibration_ram_interface_readdata,    //                                           .readdata
		output wire [8:0]  calibration_ram_s2_address,                             //                         calibration_ram_s2.address
		output wire        calibration_ram_s2_write,                               //                                           .write
		input  wire [15:0] calibration_ram_s2_readdata,                            //                                           .readdata
		output wire [15:0] calibration_ram_s2_writedata,                           //                                           .writedata
		output wire [1:0]  calibration_ram_s2_byteenable,                          //                                           .byteenable
		output wire        calibration_ram_s2_chipselect,                          //                                           .chipselect
		output wire        calibration_ram_s2_clken                                //                                           .clken
	);

	wire         sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_waitrequest;   // calibration_ram_s2_translator:uav_waitrequest -> sensor_interface_calibration_ram_interface_translator:uav_waitrequest
	wire  [15:0] sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_readdata;      // calibration_ram_s2_translator:uav_readdata -> sensor_interface_calibration_ram_interface_translator:uav_readdata
	wire         sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_debugaccess;   // sensor_interface_calibration_ram_interface_translator:uav_debugaccess -> calibration_ram_s2_translator:uav_debugaccess
	wire   [9:0] sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_address;       // sensor_interface_calibration_ram_interface_translator:uav_address -> calibration_ram_s2_translator:uav_address
	wire         sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_read;          // sensor_interface_calibration_ram_interface_translator:uav_read -> calibration_ram_s2_translator:uav_read
	wire   [1:0] sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_byteenable;    // sensor_interface_calibration_ram_interface_translator:uav_byteenable -> calibration_ram_s2_translator:uav_byteenable
	wire         sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_readdatavalid; // calibration_ram_s2_translator:uav_readdatavalid -> sensor_interface_calibration_ram_interface_translator:uav_readdatavalid
	wire         sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_lock;          // sensor_interface_calibration_ram_interface_translator:uav_lock -> calibration_ram_s2_translator:uav_lock
	wire         sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_write;         // sensor_interface_calibration_ram_interface_translator:uav_write -> calibration_ram_s2_translator:uav_write
	wire  [15:0] sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_writedata;     // sensor_interface_calibration_ram_interface_translator:uav_writedata -> calibration_ram_s2_translator:uav_writedata
	wire   [1:0] sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_burstcount;    // sensor_interface_calibration_ram_interface_translator:uav_burstcount -> calibration_ram_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (9),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (10),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) sensor_interface_calibration_ram_interface_translator (
		.clk                    (sys_clk_clk_clk),                                                                               //                       clk.clk
		.reset                  (sensor_interface_rst_reset_bridge_in_reset_reset),                                              //                     reset.reset
		.uav_address            (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (sensor_interface_calibration_ram_interface_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (sensor_interface_calibration_ram_interface_waitrequest),                                        //                          .waitrequest
		.av_read                (sensor_interface_calibration_ram_interface_read),                                               //                          .read
		.av_readdata            (sensor_interface_calibration_ram_interface_readdata),                                           //                          .readdata
		.av_burstcount          (1'b1),                                                                                          //               (terminated)
		.av_byteenable          (2'b11),                                                                                         //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                                          //               (terminated)
		.av_readdatavalid       (),                                                                                              //               (terminated)
		.av_write               (1'b0),                                                                                          //               (terminated)
		.av_writedata           (16'b0000000000000000),                                                                          //               (terminated)
		.av_lock                (1'b0),                                                                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                                          //               (terminated)
		.uav_clken              (),                                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                                         //               (terminated)
		.av_response            (),                                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (9),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (10),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) calibration_ram_s2_translator (
		.clk                    (sys_clk_clk_clk),                                                                               //                      clk.clk
		.reset                  (sensor_interface_rst_reset_bridge_in_reset_reset),                                              //                    reset.reset
		.uav_address            (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (sensor_interface_calibration_ram_interface_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (calibration_ram_s2_address),                                                                    //      avalon_anti_slave_0.address
		.av_write               (calibration_ram_s2_write),                                                                      //                         .write
		.av_readdata            (calibration_ram_s2_readdata),                                                                   //                         .readdata
		.av_writedata           (calibration_ram_s2_writedata),                                                                  //                         .writedata
		.av_byteenable          (calibration_ram_s2_byteenable),                                                                 //                         .byteenable
		.av_chipselect          (calibration_ram_s2_chipselect),                                                                 //                         .chipselect
		.av_clken               (calibration_ram_s2_clken),                                                                      //                         .clken
		.av_read                (),                                                                                              //              (terminated)
		.av_begintransfer       (),                                                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                                                              //              (terminated)
		.av_burstcount          (),                                                                                              //              (terminated)
		.av_readdatavalid       (1'b0),                                                                                          //              (terminated)
		.av_waitrequest         (1'b0),                                                                                          //              (terminated)
		.av_writebyteenable     (),                                                                                              //              (terminated)
		.av_lock                (),                                                                                              //              (terminated)
		.uav_clken              (1'b0),                                                                                          //              (terminated)
		.av_debugaccess         (),                                                                                              //              (terminated)
		.av_outputenable        (),                                                                                              //              (terminated)
		.uav_response           (),                                                                                              //              (terminated)
		.av_response            (2'b00),                                                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                           //              (terminated)
	);

endmodule
