// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Tue Jun 25 14:34:30 2024

sensor_algo sensor_algo_inst
(
	.clk_50m_clk(clk_50m_clk_sig) ,	// input  clk_50m_clk_sig
	.reset_reset_n(reset_reset_n_sig) ,	// input  reset_reset_n_sig
	.sensor_in_trg(sensor_in_trg_sig) ,	// input  sensor_in_trg_sig
	.sensor_out_adc_clk(sensor_out_adc_clk_sig) ,	// output  sensor_out_adc_clk_sig
	.sensor_out_adc_cnv(sensor_out_adc_cnv_sig) ,	// output  sensor_out_adc_cnv_sig
	.sensor_in_adc_data(sensor_in_adc_data_sig) ,	// input [4:0] sensor_in_adc_data_sig
	.sensor_out_sensor_rst(sensor_out_sensor_rst_sig) ,	// output  sensor_out_sensor_rst_sig
	.sensor_out_sensor_clk(sensor_out_sensor_clk_sig) ,	// output  sensor_out_sensor_clk_sig
	.sensor_out_sensor_gain(sensor_out_sensor_gain_sig) ,	// output  sensor_out_sensor_gain_sig
	.sensor_csr_address(sensor_csr_address_sig) ,	// input [1:0] sensor_csr_address_sig
	.sensor_csr_read(sensor_csr_read_sig) ,	// input  sensor_csr_read_sig
	.sensor_csr_readdata(sensor_csr_readdata_sig) ,	// output [31:0] sensor_csr_readdata_sig
	.sensor_csr_write(sensor_csr_write_sig) ,	// input  sensor_csr_write_sig
	.sensor_csr_writedata(sensor_csr_writedata_sig) ,	// input [31:0] sensor_csr_writedata_sig
	.sensor_csr_byteenable(sensor_csr_byteenable_sig) ,	// input [3:0] sensor_csr_byteenable_sig
	.sensor_status_status_out(sensor_status_status_out_sig) ,	// output [7:0] sensor_status_status_out_sig
	.sensor_synchro_serial_rx(sensor_synchro_serial_rx_sig) ,	// input  sensor_synchro_serial_rx_sig
	.sensor_synchro_serial_tx(sensor_synchro_serial_tx_sig) ,	// output  sensor_synchro_serial_tx_sig
	.sensor_synchro_ext_input(sensor_synchro_ext_input_sig) 	// input [7:0] sensor_synchro_ext_input_sig
);

